### ISSUE TITLE
Change the background

### ISSUE THREAD

**Issue by larister** [asyncjs/Fishcotheque#1]
Currently, it looks like a jungle. The background is quite dynamic though, with a lot of the environment being generated in /javascript. Could we modify any of these to suit our purposes? We should probably remove the code to change day to night as well

---
- Remove day/night
- Remove trees
- Remove stars
- Remove grass
- Add sea/waves
- Add sea bed
- Add other environmental things - bubbles, coral, plants etc

**Comment by orangespaceman** [comment]
I'm happy to do this one, feel free to assign it to me.

**Comment by larister** [comment]
w00t! Thanks @thegingerbloke
